apiVersion: v1
kind: ServiceAccount
metadata:
  name: genesis-app
  namespace: genesis
  labels:
    app: genesis-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: genesis-app-vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: genesis-app
  namespace: genesis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: genesis-app-vault-secret-reader
  namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-secret-reader
subjects:
- kind: ServiceAccount
  name: genesis-app
  namespace: genesis
