apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-api
spec:
  replicas: {{ .Values.commandApi.replicas }}
  selector:
    matchLabels:
      app: command-api
  template:
    metadata:
      labels:
        app: command-api
    spec:
      containers:
        - name: command-api
          image: {{ .Values.commandApi.image }}
          command: ["python", "run_command.py"]
          ports:
            - containerPort: 8000
