apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-api
spec:
  replicas: {{ .Values.grpcApi.replicas }}
  selector:
    matchLabels:
      app: grpc-api
  template:
    metadata:
      labels:
        app: grpc-api
    spec:
      containers:
        - name: grpc-api
          image: {{ .Values.grpcApi.image }}
          command: ["python", "run_grpc.py"]
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-api
spec:
  selector:
    app: grpc-api
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
